#!/bin/bash

# shellcheck disable=SC1091
# shellcheck disable=SC2002


set -o errexit
set -o nounset
set -o pipefail

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libfs.sh

# Load Global/Yearning environment variables
. /etc/s6/s6-init/envs

#=====================#
#   Prepare Yearning       #
#=====================#
YearningCfg="/apps/yearning/conf.toml"

info "Render conf.toml with environment variables."
/usr/bin/render-template ${YearningCfg}.tpl > ${YearningCfg}

cat ${YearningCfg}

#======================#
# Check MySQL service  #
#======================#
# Check and waiting mysql to be ready
wait_for_mysql || exit 1

# Initialize database
mysql_init_db "$DB_NAME"

if [ ! -f "/data/.init_cfg" ]; then
  info "Initialize Yearning"
  /apps/yearning/Yearning install --config "${YearningCfg}"
  echo "$YEARNING_VERSION" > /data/.now_version
  touch /data/.init_cfg
else
  cat /data/.now_version | grep "$YEARNING_VERSION" || (
    info "Check Upgrade"
    /apps/yearning/Yearning migrate --config "${YearningCfg}"
    echo "$YEARNING_VERSION" > /data/.now_version
  )
fi

